### ISSUE TITLE
Carbon\Exceptions\InvalidTimeZoneException    Unknown or bad timezone (Error: Could not connect to database.)

### ISSUE THREAD

**Issue by md-asifiqbal** [abdelmjid-saber/SpladePanel#1]
Showing error on composer install 

   Carbon\Exceptions\InvalidTimeZoneException

  Unknown or bad timezone (Error: Could not connect to database.)

  at vendor\nesbot\carbon\src\Carbon\CarbonTimeZone.php:109
    105▕             return new static($tz->getName());
    106▕         }
    107▕
    108▕         if (Carbon::isStrictModeEnabled()) {
  ➜ 109▕             throw new InvalidTimeZoneException('Unknown or bad timezone ('.($objectDump ?: $object).')');
    110▕         }
    111▕
    112▕         return false;
    113▕     }

  1   vendor\nesbot\carbon\src\Carbon\Traits\Date.php:626
      Carbon\CarbonTimeZone::instance("Error: Could not connect to database.")

  2   vendor\nesbot\carbon\src\Carbon\Traits\Date.php:1631
      Carbon\Carbon::safeCreateDateTimeZone("Error: Could not connect to database.")

**Comment by megoxv** [comment]
Issue resolved. Please try updating the project and see if the problem is resolved.

If you encounter any further issues or need assistance, feel free to ask.

**Comment by MotionPhix** [comment]
While you have marked this issue as closed, I just downloaded the repo today and I am still facing the same issue:

 ```
 Carbon\Exceptions\InvalidTimeZoneException

  Unknown or bad timezone (Error: Could not connect to database.)

  at vendor\nesbot\carbon\src\Carbon\CarbonTimeZone.php:109
    105▕             return new static($tz->getName());
    106▕         }
    107▕
    108▕         if (Carbon::isStrictModeEnabled()) {
  ➜ 109▕             throw new InvalidTimeZoneException('Unknown or bad timezone ('.($objectDump ?: $object).')');
    110▕         }
    111▕
    112▕         return false;
    113▕     }

  1   vendor\nesbot\carbon\src\Carbon\Traits\Date.php:626
      Carbon\CarbonTimeZone::instance("Error: Could not connect to database.")

  2   vendor\nesbot\carbon\src\Carbon\Traits\Date.php:1631
      Carbon\Carbon::safeCreateDateTimeZone("Error: Could not connect to database.")
```

**Comment by AnowarDotDev** [comment]
I've also got that issue!

**Comment by megoxv** [comment]
following steps:

1. Delete the `.env` file.
2. Try running `composer install`.
