### ISSUE TITLE
Plugin Option

### ISSUE THREAD

**Issue by MdAnowarHosen** [abdelmjid-saber/SpladePanel#2]
Can you please more details us about plugin option? How can we use it?

**Comment by megoxv** [comment]
Certainly! The plugin option you're referring to is related to utilizing the nWidart/laravel-modules package within Laravel applications. This package facilitates the organization of your Laravel codebase into modular components, akin to plugins.

To utilize these plugins:

- Module Creation: Generate a new module using the command php artisan module:make ModuleName.
- Module Structure: Each module will possess its directory structure, housing various components like controllers, views, routes, and more.
- Configuration: Configure modules individually by modifying their configuration files within the config/modules directory.
- Module.json: This file outlines the name, alias, description, and options of the module:
```
 {
    "name": "Team",
    "alias": "teams",
    "icon": "fal fa-users",
    "title": "Team",
    "description": "Through this add-on, you can manage your work team.",
    "color": "#03a9f4",
    "version": "1.0",
    "author": "Abdelmjid",
    "keywords": [],
    "priority": 0,
    "providers": [
        "Modules\\Team\\Providers\\TeamServiceProvider"
    ],
    "files": []
}

```

- Routing: Define module-specific routes within the Routes directory.
- Accessing Modules: Access module routes and features using the module name as part of the URL, e.g., http://127.0.0.1:8000/module-name.
- Other Commands: The package furnishes diverse commands to manage modules, including generating controllers, models, views, and more, tailored to each module.

Please bear in mind that this serves as a simplified guide on how to employ the plugins package. For more comprehensive instructions and advanced usage, consult the package's documentation at [https://docs.laravelmodules.com/](https://docs.laravelmodules.com/).
