### ISSUE TITLE
Carbon\Exceptions\InvalidTimeZoneException

### ISSUE THREAD

**Issue by bhattji** [abdelmjid-saber/SpladePanel#3]
Carbon\Exceptions\InvalidTimeZoneException

  Unknown or bad timezone (Error: Could not connect to database.)

  at vendor\nesbot\carbon\src\Carbon\CarbonTimeZone.php:109
    105▕             return new static($tz->getName());
    106▕         }
    107▕
    108▕         if (Carbon::isStrictModeEnabled()) {
  ➜ 109▕             throw new InvalidTimeZoneException('Unknown or bad timezone ('.($objectDump ?: $object).')');
    110▕         }
    111▕
    112▕         return false;
    113▕     }

  1   vendor\nesbot\carbon\src\Carbon\Traits\Date.php:626
      Carbon\CarbonTimeZone::instance()

  2   vendor\nesbot\carbon\src\Carbon\Traits\Date.php:1631
      Carbon\Carbon::safeCreateDateTimeZone()

**Comment by megoxv** [comment]
Thank you for bringing this issue to our attention, and I apologize for any inconvenience you've experienced. I understand that you're encountering a problem similar to the one mentioned in the provided GitHub issue: https://github.com/abdelmjid-saber/SpladePanel/issues/1

Quick solution

1. Delete the .env file.
2. Try running composer install.

**Comment by megoxv** [comment]
If the issue remains unresolved, update the project. The problem has been resolved in the latest update.
