### ISSUE TITLE
Can we use a better theme? viz Splaragon?

### ISSUE THREAD

**Issue by bhattji** [abdelmjid-saber/SpladePanel#4]
Can we use a better theme? viz Splaragon? https://github.com/maina401/splaragon

I did try, but could not make it work

**Comment by megoxv** [comment]
Absolutely! We're eagerly anticipating the upcoming updates, as the theme is slated for a refresh. We're striving to enhance the user experience and bring a more appealing look and feel. Stay tuned for the exciting changes! 🌟🎉
